import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'


import { Providers, NextLayout } from '@/app/provider'


const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter'
})
const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.variable}`}>
        <Providers>
          <NextLayout>
            {children}
          </NextLayout>
        </Providers>
      </body>
    </html>
  )
}